---
title: "bitpanda"
author: "Xinyue Zhang, Hanyu Wang, Harsh Tripathi"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
library(geckor)
library(tidyverse)
library(ggplot2)
library(magrittr)
library(httr)
library(jsonlite)
```

```{r}
pantos_history <- coin_history(coin_id="pantos", 
                               vs_currency="usd", 
                               days = 'max', 
                               interval=NULL)

pantos_history<- pantos_history %>% mutate(market_cap= case_when(coin_id =="pantos" ~price* 486161689,TRUE ~ market_cap)) %>%
                                    mutate(net_ret = (price-lag(price))/lag(price) *100) %>%
                                    mutate(change_tv = (total_volume-lag(total_volume))/lag(total_volume) *100) %>%
                                    mutate(change_mc = (market_cap-lag(market_cap))/lag(market_cap) *100) %>%
                                    mutate(liquility = (total_volume/price))
```


```{r}
polkadot_history <- coin_history(coin_id = "polkadot", 
                                vs_currency = "usd", 
                                days = "max",
                                interval = NULL)

polkadot_history<- polkadot_history %>% mutate(net_ret = (price-lag(price))/lag(price) *100) %>%
                                    mutate(change_tv = (total_volume-lag(total_volume))/lag(total_volume) *100) %>%
                                    mutate(change_mc = (market_cap-lag(market_cap))/lag(market_cap) *100)%>%
                                    mutate(liquility = (total_volume/price))
```


```{r}
cosmos_history <- coin_history(coin_id = "cosmos", 
                                vs_currency = "usd", 
                                days= 'max',
                                interval = NULL)

cosmos_history<- cosmos_history %>% mutate(net_ret = (price-lag(price))/lag(price) *100) %>%
                                    mutate(change_tv = (total_volume-lag(total_volume))/lag(total_volume) *100) %>%
                                    mutate(change_mc = (market_cap-lag(market_cap))/lag(market_cap) *100)%>%
                                    mutate(liquility = (total_volume/price))
```


```{r}
harmony_history <- coin_history(coin_id = "harmony", 
                                vs_currency = "usd", 
                                days= 'max',
                                interval = NULL)

harmony_history<- harmony_history %>% mutate(net_ret = (price-lag(price))/lag(price) *100) %>%
                                    mutate(change_tv = (total_volume-lag(total_volume))/lag(total_volume) *100) %>%
                                    mutate(change_mc = (market_cap-lag(market_cap))/lag(market_cap) *100)%>%
                                    mutate(liquility = (total_volume/price))
```


```{r}
best_history <- coin_history(coin_id = "bitpanda-ecosystem-token", 
                                vs_currency = "usd", 
                                days= 'max',
                                interval = NULL)

best_history<- best_history %>% mutate(net_ret = (price-lag(price))/lag(price) *100) %>%
                                    mutate(change_tv = (total_volume-lag(total_volume))/lag(total_volume) *100) %>%
                                    mutate(change_mc = (market_cap-lag(market_cap))/lag(market_cap) *100)%>%
                                    mutate(liquility = (total_volume/price))
```


```{r}
bnb_history <- coin_history(coin_id = "binancecoin", 
                                vs_currency = "usd", 
                                days= 'max',
                                interval = NULL)

bnb_history<- bnb_history %>% mutate(net_ret = (price-lag(price))/lag(price) *100) %>%
                                    mutate(change_tv = (total_volume-lag(total_volume))/lag(total_volume) *100) %>%
                                    mutate(change_mc = (market_cap-lag(market_cap))/lag(market_cap) *100)%>%
                                    mutate(liquility = (total_volume/price))
```

```{r}
tcap_history <- coin_history(coin_id = "total-crypto-market-cap-token", 
                                vs_currency = "usd", 
                                days= 'max',
                                interval = NULL)

tcap_history<- tcap_history %>% mutate(net_ret = (price-lag(price))/lag(price) *100) %>%
                                    mutate(change_tv = (total_volume-lag(total_volume))/lag(total_volume) *100) %>%
                                    mutate(change_mc = (market_cap-lag(market_cap))/lag(market_cap) *100)%>%
                                    mutate(liquility = (total_volume/price))
```


```{r}
history<- rbind(pantos_history, polkadot_history, cosmos_history, harmony_history,
                best_history, bnb_history, tcap_history)
history
```



```{r}
#Using cryptocompare API to get data for Pantos (coinId = 837419)
res = GET("https://min-api.cryptocompare.com/data/social/coin/histo/day?coinId=837419&aggregate=7&api_key=bebc9e1c95f5963fc7f09dfc7995acb7478e3e970dba3b6c40974c7c859ff07a")

#Checking if API call was successful
if(res$status_code == 200){
    #Converting raw unicode data to JSON and then a list and finally extracting data frame
    social_media_data = fromJSON(rawToChar(res$content))$Data
    
    #Converting UNIX timestamp to date
    social_media_data$time <- as.POSIXct(social_media_data$time, origin = "1970-01-01")
    
    #Renaming column
    names(social_media_data)[names(social_media_data) == 'time'] <- 'timestamp'
    
    #List of relevant columns
    relevant_columns = c('timestamp', 'twitter_followers', 'twitter_favourites', 'reddit_subscribers', 'reddit_active_users', 'reddit_posts_per_day', 'fb_likes')
    
    #Selecting relevant columns
    social_media_data <- social_media_data %>% 
      select(relevant_columns)
    
    #Extracting date in social media dataset to merge
    social_media_data$date <- as.Date(social_media_data$timestamp)
    
    #Removing timestamp from social media data
    social_media_data <- social_media_data %>%
      select(-timestamp)
    
    #Extracting date in history dataset to merge
    history$date <- as.Date(history$timestamp)
    
    #Adding coin_id to social media dataset to merge
    social_media_data$coin_id <- 'pantos'
    
    #Merging the data
    history <- left_join(history, social_media_data, by = c('date', 'coin_id'))
    
    #Dropping the date column
    history <- history %>%
      select(-date)
    }
```



There are some infinite values and cuased error when saving into Google sheet.
```{r}
history[sapply(history, is.infinite)] <- NaN
```

```{r}
write.csv(history,file="history.csv")
```

# connect to Google sheet
```{r}
#code below only needs to be run once, it will guide you to connect to google account
library(googlesheets4)
library(googledrive)
options(gargle_oauth_cache = ".secrets")
drive_auth(cache = ".secrets", email = "hanyuwangofficial@gmail.com")# email="" change to your own Google account
gs4_auth(token = drive_token())

```



```{r}
history_gs<- gs4_create(
  "history", # file name
  sheets =history #data source
)
```

```{r}
write_sheet(history, ss = '1jeU0eiOnYAL4yhaZ0Ot9eRZ5HR4kXgyYZl4yPofPwcw', sheet = 'history')
```


```{r}
# history %>% 
#   #filter(coin_id %in% c("cosmos","harmony")) %>% 
#   ggplot()+
#   geom_line(aes(x=timestamp,y=price,color=coin_id))
      
```


